---
title: "TNBC_fglm"
#date: '`r format(Sys.time(), "%Y-%m-%d")`'
output:
  html_document: 
    code_folding: hide
    toc: true
    toc_float: true
hitheme: tomorrow
highlighter: highlight.js
---

#-----------------------------------------------------------------------------##-----------------------------------------------------------------------------#
```{r setup , include=FALSE}
library(survival)
library(survminer)
library(dplyr)
library(tidyverse)
library(readxl)
library(janitor)
library(skimr)
library(phenoptr)
library(phenoptrReports)
library(rtree)
library(data.table)
library(pivottabler)
library(ggpubr)
library(zoo)
library(lubridate)
library(reReg)
library(spatstat)
library(mgcv)
library(refund)
library(ggplot2)
library(gridExtra)
library(gtools)
library(raster)
knitr::opts_chunk$set(echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 6
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```


# Load source functions
```{r}
source_dir = "~/Documents/Imaging project/Vectra /" 
source(paste0(source_dir, "ref_functions.R"))
```

# read in TNBC clinical data
```{r, warning=FALSE}
CDir =  "~/Documents/Imaging project/Vectra /TNBC_shareCellData/"
tnbc = read.csv(paste0(CDir, "cellData.csv"))
tnbc_class = read.csv(paste0(CDir, "patient_class.csv"), header = F)#[,2] 
colnames(tnbc_class) = c("InternalId", "patient_class")
#0: (mixed) tumor mixed with immune cells
#1: (compartmentalized) tumor cells and immune cells spatially separated
#2: (cold): no infiltrate
tnbc_clinical = read_excel(paste0(CDir, "tnbc_clinical.xlsx"), skip = 1, n_max = 40)
```


# load tif images
```{r, warning=FALSE}
# PREPROCESS DATA
# read in multiple tiff files
# there's no subject ID 30 in the csv file
setwd("~/Documents/Imaging project/Vectra /TNBC_shareCellData")
temp_file = list.files(pattern = "*.tiff")
temp_file = mixedsort(temp_file) # reverse the name ordering
all_file = lapply(temp_file, raster) #2048x2048 images
pixel_xy  = lapply(all_file, function(x) coordinates(x)) 
pixel_val = lapply(all_file, function(x) as.vector(x)) 
N = length(all_file)
all_idx = lapply(seq(1, N, 1), function(x) which(tnbc$SampleID == x))
# extract locations & pixel values
center_x = list()
center_y = list()
for (i in 1:N){
  #print(i)
  temp_idx = all_idx[[i]]
  temp_val = pixel_val[[i]]
  temp_xy = pixel_xy[[i]]
  temp_val = lapply(tnbc$cellLabelInImage[temp_idx], function(x) which(temp_val == x))
  center_x[[i]] = lapply(temp_val, function(x) mean(temp_xy[x,1]))
  center_y[[i]] = lapply(temp_val, function(x) mean(temp_xy[x,2]))
}
```



```{r, warning=FALSE}
# CENSORED: 1 = censored, 0 = death
# Reproduce Fig 7 of the Cell paper Keren et al (2018)
# for compartmentalized (1) vs mixed class(0)
test_df = tnbc_clinical
test_df = left_join(test_df, tnbc_class, by = "InternalId")
# remove class 2
test_df = test_df[-which(test_df$patient_class == 2),]
                
test_df$patient_class = as.factor(test_df$patient_class)
surv_obj = Surv(test_df$`Survival_days_capped*`/365, event = ifelse(test_df$Censored == 1, 0, 1))
# Kaplan_Meier curve
test_fit = survfit(surv_obj ~ patient_class, data = test_df)
# plot survival curve
ggsurvplot(test_fit, data = test_df, pval = TRUE)
test_coxph = coxph(formula = surv_obj ~ patient_class, data = test_df)
```

```{r, warning=FALSE, message=FALSE}
# pixel-level images
plt_group = c(1,2)
plt = list()
for(i in plt_group){
df = data.frame(x = pixel_xy[[i]][,1], y =  pixel_xy[[i]][,2], val = pixel_val[[i]])

plt[[i]] = ggplot(df, aes(x = x, y =y)) + geom_point(aes(colour = val)) + xlab("X position") + ylab("Y position")   + theme(plot.title = element_text(hjust = 0.5))+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +  scale_color_gradientn(colours = rainbow((5)))
}

plt[plt_group]
```


```{r, warning=FALSE}
#cell_level figures
center_x = lapply(center_x, unlist)
center_y = lapply(center_y, unlist)
plt_group = c(1,2)
plt = list()
for(i in plt_group){
df = data.frame(x = center_x[[i]], y =  center_y[[i]], val = tnbc$cellLabelInImage[all_idx[[i]]])

plt[[i]] = ggplot(df, aes(x = x, y =y)) + geom_point(aes(colour = val)) + xlab("X position") + ylab("Y position")   + theme(plot.title = element_text(hjust = 0.5))+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +  scale_color_gradientn(colours = rainbow((5)))
}

plt[plt_group]

```


```{r, warning=FALSE, message=FALSE}
# cell-level figures using cell types: keratin-positive tumor (6) vs others (1-5)
# 1: unidentified, 2: Immune, 3: Endothelial, 4: Mesenchymal-like, 5: Tumor, 6: keratin-positive tumor
plt_group = c(1,2)
plt = list()
for(i in plt_group){
df = data.frame(x = center_x[[i]], y =  center_y[[i]], cell_group = as.factor(tnbc$Group[all_idx[[i]]]))
levels(df$cell_group) = c("Unidentified", "Immune", "Endothelial", "Mesenchymal-like", "Tumor", "CK+ Tumor")

plt[[i]] = ggplot(df, aes(x = x, y = y, col = cell_group)) + geom_point(size = 0.001 * tnbc$cellSize[all_idx[[i]]]) + xlab("X position") + ylab("Y position")   + theme(plot.title = element_text(hjust = 0.5))+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) 
}

plt[plt_group]
```



```{r, warning=FALSE}
## plot survival time for each patient with shapes indicating censoring or event

plt_group = c(1:5)
t_censor = factor(tnbc_clinical$Censored)
levels(t_censor)[levels(t_censor) == "1"] = "Censored"
levels(t_censor)[levels(t_censor) == "0"] = "Mortality"

surv_patient = tibble(Subject = as.factor(c("P1", "P2", "P3", "P4", "P5")), Years = as.numeric(tnbc_clinical$`Survival_days_capped*`/365)[plt_group], censor = t_censor[plt_group])
# plot with shapes to indicate censoring or event
ggplot(surv_patient, aes(Subject, Years)) + 
    geom_bar(stat = "identity", width = 0.1) + 
    geom_point(data = surv_patient, 
               aes(Subject, Years, color = censor, shape = censor), 
               size = 6) +
    coord_flip() +
    theme_minimal() + 
    theme(legend.title = element_blank(),
          legend.position = "bottom")
```



# CK+ tumor vs immune cells
```{r}
subset_idx = list()
for (i in 1:N){
  temp_idx = all_idx[[i]]
  subset_idx[[i]] = c(which(tnbc$Group[temp_idx] == 2), which(tnbc$Group[temp_idx] == 6))
}
```


```{r}
plt_group = c(which(tnbc_class$patient_class == 2))
plt = list()
for(i in plt_group){
temp = subset_idx[[i]]
x_pos = center_x[[i]][temp]
y_pos = center_y[[i]][temp]
temp_group = all_idx[[i]][temp]
df = data.frame(x = x_pos, y = y_pos, cell_group = as.factor(tnbc$Group[temp_group]))
levels(df$cell_group) = c( "Immune", "CK+ Tumor")

plt[[i]] = ggplot(df, aes(x = x, y = y, col = cell_group)) + geom_point(size = 0.001 * tnbc$cellSize[subset_idx[[i]]]) + xlab("X position") + ylab("Y position")   + theme(plot.title = element_text(hjust = 0.5))+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) 
}

plt[plt_group]
```


```{r}
# temporary group for "CK+ tumor" vs "Immune"
tnbc$tempgroup[tnbc$Group == 6] = "Tumor"
tnbc$tempgroup[which(tnbc$Group == 2)] = "Immune"
```


```{r, warning=FALSE}
# use patient 16 as reference since it has the most cells
i = 16
temp = subset_idx[[i]]
x_pos = center_x[[i]][temp]
y_pos = center_y[[i]][temp]
temp_group = all_idx[[i]][temp]
patient1 = ppp(x_pos, y_pos, c(min(x_pos), max(x_pos)), c(min(y_pos), max(y_pos))) 
patient1 = patient1 %mark% as.factor(tnbc$tempgroup[temp_group])
patient1_mcf = markconnect(patient1, "Tumor", "Immune", normalise = TRUE) 
common_r = patient1_mcf$r
n_r = length(common_r)

t1 = Sys.time()
# subject 30 doesn't have cell-level data
new_mcf_iso = matrix(0, N, n_r) #Ripley isotropic correction estimate 
new_mcf_trans = matrix(0, N, n_r) #translation-corrected estimate 


for (i in 1:N){
  if(i %% 20 == 0){
    cat(paste0("iteration: ", i, "\n"))
  }
  if(i == 30){next}
  else{
  temp = subset_idx[[i]]
  x_pos = center_x[[i]][temp]
  y_pos = center_y[[i]][temp]
  temp_group = all_idx[[i]][temp]
  patient_i = ppp(x_pos, y_pos, c(min(x_pos), max(x_pos)), c(min(y_pos), max(y_pos))) 
  patient_i = patient_i %mark% as.factor(tnbc$tempgroup[temp_group])
  mcf_i = markconnect(patient_i, "Tumor", "Immune", normalise = TRUE) 

  new_mcf_trans[i,] = mcf_i$trans
  new_mcf_iso[i,] = mcf_i$iso
  }
}
t2 = Sys.time()
t2-t1
```

#mcf curves for all subjects
```{r, warning=FALSE}
df <- NULL
for(i in 1:N){
  if(i == 30){next}
  else{
  temp_df <- data.frame(x=common_r, y=new_mcf_trans[i,], col= i)
df <- rbind(df,temp_df)} }

ggplot(df,aes(x = x, y = y, group=col)) + geom_line(alpha = .5) +  xlab("r (pixels)") + ylim(0,1.2) + ylab("mcf") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+ geom_hline(yintercept=1, linetype="dashed", color = "black") + theme(legend.position="none")

```



```{r}
# Figure 4 (b, c)
mcf = new_mcf_trans 
# cold
df_2 <- NULL
for(i in which(tnbc_class$patient_class == 2)){
  temp_2 <- data.frame(x=common_r, y=mcf[i,], Patient = i)
  df_2 <- rbind(df_2,temp_2)} 
ggplot(df_2,aes(x = x, y = y, group = Patient)) + geom_line(alpha = 0.4) +  xlab("r (pixels)") + ylim(0,1.2) + ylab("mcf") + ggtitle("Cold") + geom_hline(yintercept=1, linetype="dashed", color = "black")+ theme(plot.title = element_text(hjust = 0.5)) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
# mixed
df_0 <- NULL
for(i in which(tnbc_class$patient_class == 0)){
  if(i == 30){next}
  else{
  temp_0 <- data.frame(x=common_r, y=mcf[i,], Patient= i)
  df_0 <- rbind(df_0,temp_0)}}
ggplot(df_0,aes(x = x, y = y, group = Patient)) + geom_line(alpha = 0.4) +  xlab("r (pixels)") + ylim(0,1.2)+ ylab("mcf") + geom_hline(yintercept=1, linetype="dashed", color = "black") +  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(legend.position="none")
# compartmentalized
df_1 <- NULL
for(i in which(tnbc_class$patient_class == 1)){
  temp_1 <- data.frame(x=common_r, y = mcf[i,], Patient = i)
  df_1 <- rbind(df_1,temp_1)} 
ggplot(df_1,aes(x = x, y = y, group = Patient)) + geom_line(alpha = 0.4) +  xlab("r (pixels)")+ ylim(0,1.2) + ylab("mcf") +geom_hline(yintercept=1, linetype="dashed", color = "black")+  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+ theme(legend.position="none")
```



```{r, warning=FALSE, message=FALSE}
# Figure 4 a, b
# representative image for manuscript: mixed vs compartmentalized
plt_group = c(5,11) 
plt = list()
for(i in plt_group){
df = data.frame(x = center_x[[i]], y =  center_y[[i]], cell_group = as.factor(tnbc$agg_group[all_idx[[i]]]))

plt[[i]] = ggplot(df, aes(x = x, y =y, col = cell_group)) + geom_point(size = 0.7) + theme(plot.title = element_text(hjust = 0.5))+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme_void() + theme(legend.position="none")
}
plt[plt_group]
```


```{r, warning=FALSE}
# FIT MODEL WITH NORM_MCF
k = 6# num basis functions
# transfer pixels to microns
common_r1 = common_r * 0.39
# patients 22, 38 don't have outcome info
norm_mcf = new_mcf_trans[-c(22,30,38),] #new_mcf_trans
p = dim(norm_mcf)[2]
# functional observations
X_obs <- fpca.face(norm_mcf)$Yhat #with or without fpca.face(), doesn't make big difference
# data combined
# event, survival time, Z, functional covariates
test_df = tnbc_clinical
test_df = left_join(test_df, tnbc_class, by = "InternalId")
# remove patient 30
test_df = test_df[-which(test_df$InternalId == 30),]
            
test_df$patient_class = as.factor(test_df$patient_class)


data_combine = data.frame(event = ifelse(test_df$Censored == 1, 0,1), stime = test_df$`Survival_days_capped*`,
                          Age = test_df$AGE_AT_DX, Grade = as.factor(test_df$GRADE),#Patient_class = test_df$patient_class,
                          X_obs = I(X_obs)) 
n_common = dim(data_combine)[1]
###########################################################################
# Fit AFCM and LFCM using mgcv
###########################################################################
## Add variables related to numerical integration
### lmat: numeric integration of the functional term
data_combine$lmat <- I(matrix(1/p, ncol=p, nrow=n_common))
### tmat: time indices, we assume an equally-spaced grid of [0, 1] for example
data_combine$tmat <-# I(matrix(seq(0, 1, len=p), ncol=p, nrow=n_common, byrow=TRUE))
                   I(matrix(seq(min(common_r1), max(common_r1), len=p), ncol=p, nrow=n_common, byrow=TRUE))


## smoothed LAC, h_{is} is the identity function
data_combine$func_cov <- data_combine$X_obs ## specify the functional covariates to use
data_combine$t_int <- data_combine$tmat ## t_int helps to integrate the case when models have different tmat and lmat
data_combine$l_int <- data_combine$lmat

fit_afcm <- gam(stime ~  Age + #Grade + #Patient_class + 
                ti(t_int, func_cov, by=l_int, bs=c("cr","cr"), k=c(k,k), mc=c(FALSE,TRUE)) 
                ,weights=event, data=data_combine, family=cox.ph())

## Fit LFCM
fit_lfcm <- gam(stime ~ Age + #Grade + #Patient_class + 
                s(t_int, by=l_int*func_cov, bs="cr", k=k) 
                , weights=event, data=data_combine, family=cox.ph())

## add other variables used in model fitting, required in predict() function
### in practice, we replicate the first row in final grid since it won't incluence estimated functional surface
sample1 <- data.frame("Age" = data_combine[1,c("Age")])# for 1 variable so that the column name is kept  # c("Age", "Grade")]  #"Patient_class")]


# extract estimates
# AFCM
grid_coef <- cal_grid(grid_length = 100, range_x = c(min(X_obs), max(X_obs)), range_s = c(min(common_r1), max(common_r1))) # range_s = c(0,1)) #
sample_rep <- do.call("rbind", replicate(nrow(grid_coef), sample1, simplify = FALSE)) # repeat first row of scalar covariates 
grid_coef <- cbind(grid_coef, sample_rep)

real_coef_afcm <- predict(fit_afcm, newdata = grid_coef, type = 'terms')

real_coef_afcm <- matrix(real_coef_afcm[,"ti(t_int,func_cov):l_int"], ncol = sqrt(nrow(grid_coef)), nrow = sqrt(nrow(grid_coef)), byrow = FALSE) # re-organize to matrix form
# LFCM
real_coef_lfcm <- predict(fit_lfcm, newdata = grid_coef, type = 'terms')
real_coef_lfcm <- matrix(real_coef_lfcm[,"s(t_int):l_int * func_cov"], ncol = sqrt(nrow(grid_coef)), nrow = sqrt(nrow(grid_coef)), byrow = FALSE) # re-organize to matrix form
```

## Plot AFCM & LFCM surface
```{r, warning=FALSE}
par(mfrow = c(1,2))
# Plot AFCM surface
real_surf_afcm <- vis_surf(coef = real_coef_afcm, simulation = TRUE, transformation = FALSE, range_x = c(min(X_obs), max(X_obs)), range_s = c(min(common_r1), max(common_r1)), 
                           trans_name = "Estimates from AFCM ")

plot(real_surf_afcm)
# Plot LFCM surface
real_surf_lfcm <- vis_surf(coef = real_coef_lfcm, simulation = TRUE, transformation = FALSE, range_x = c(min(X_obs), max(X_obs)), range_s = c(min(common_r1), max(common_r1)),
                          trans_name = "Estimates from LFCM")
                         
plot(real_surf_lfcm)

```

################################################################################
### find Moran's correlation in p53 marker between tumor cells vs immune cells
################################################################################ 

```{r, warning=FALSE}
# scale marker intensity
tnbc$p53 = (tnbc$p53 - min(tnbc$p53))/(max(tnbc$p53) - min(tnbc$p53))
tnbc$Ki67 = (tnbc$Ki67 - min(tnbc$Ki67))/(max(tnbc$Ki67) - min(tnbc$Ki67))

  i = 16 
  patient_i = all_idx[[i]]
  tumor_i = which(tnbc$Group[patient_i] == 6)
  stroma_i =  which(tnbc$Group[patient_i] == 2)
  temp = tnbc[patient_i,]
  tumor_X_pos = center_x[[i]][tumor_i]
  tumor_Y_pos = center_y[[i]][tumor_i]
  stroma_X_pos = center_x[[i]][stroma_i]
  stroma_Y_pos = center_y[[i]][stroma_i]
  
  patient_tumor = ppp(tumor_X_pos, tumor_Y_pos, c(min(tumor_X_pos), max(tumor_X_pos)), c(min(tumor_Y_pos), max(tumor_Y_pos))) 
  
  patient_stroma = ppp(stroma_X_pos, stroma_Y_pos, c(min(stroma_X_pos), max(stroma_X_pos)), c(min(stroma_Y_pos), max(stroma_Y_pos)))
  
  D12 = crossdist(patient_tumor, patient_stroma)
 
  r_max = max(D12)/4
  breaks = handle.r.b.args(r = NULL, breaks = NULL, window, pixeps = NULL, r_max)
  r_seq = breaks$r  
  
  t1 = Sys.time()
  n_patient = length(all_idx)
  moran_p53 = list()

for (i in 1: n_patient){
  if(i %% 20 == 0){
    cat(paste0("iteration: ", i, "\n"))
  }
  
  if(i == 30){next}
  else{
   # without converting images to standard unit
  patient_i = all_idx[[i]]
  tumor_i = which(tnbc$Group[patient_i] == 6)
  stroma_i =  which(tnbc$Group[patient_i] == 2)
  temp = tnbc[patient_i,]
  tumor_X_pos = center_x[[i]][tumor_i]
  tumor_Y_pos = center_y[[i]][tumor_i]
  stroma_X_pos = center_x[[i]][stroma_i]
  stroma_Y_pos = center_y[[i]][stroma_i]
  
  patient_tumor = ppp(tumor_X_pos, tumor_Y_pos, c(min(tumor_X_pos), max(tumor_X_pos)), c(min(tumor_Y_pos), max(tumor_Y_pos))) 
  
  patient_stroma = ppp(stroma_X_pos, stroma_Y_pos, c(min(stroma_X_pos), max(stroma_X_pos)), c(min(stroma_Y_pos), max(stroma_Y_pos)))
  
  patient_tumor = patient_tumor %mark% cbind(p53 = tnbc$p53[tumor_i], ki67 = tnbc$Ki67[tumor_i])
                                 
  patient_stroma = patient_stroma %mark% cbind(p53 = tnbc$p53[stroma_i], ki67 = tnbc$Ki67[stroma_i])
  
   moran_p53[[i]] = moran_cross(patient_tumor, patient_stroma, 1, 4, r_seq)
   #moran_ki67[[i]] = moran_cross(patient_tumor, patient_stroma, 2, 4, r_seq)
  }
}
t2 = Sys.time()
t2-t1
```


```{r}

moran_p53_mat = matrix(0, n_patient, p)
for (i in 1:n_patient){
  if(i == 30){next}
  else{
  moran_p53_mat[i,] = moran_p53[[i]]$moran_est
  }
}
```


```{r}
# Fig 5b. 
df <- NULL
for(i in c(1:n_patient)[-c(22,30,38)]){
  temp_df <- data.frame(x=r_seq*0.39, y=moran_p53_mat[i,], col=i)
  df <- rbind(df,temp_df)} 
ggplot(df,aes(x = x, y = y, group=col)) + geom_line(alpha = 0.4) +  xlab("r (microns)") + ylab("Moran's") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(legend.position = "none")

```


```{r, warning=FALSE}
# FIT MODEL WITH NORM_MCF
k = 6# num basis functions
# transfer pixels to microns
common_r1 = r_seq * 0.39
# patients 22, 38 don't have outcome info
norm_mcf = moran_p53_mat[-c(22,30,38),] #new_mcf_trans[-c(22,30,38),] #markcorr_trans[-c(22,30,38),]
p = dim(norm_mcf)[2]


#norm_mcf <- I(apply(norm_mcf, 2,function(y) ecdf(y)(y)))
#X_obs = norm_mcf

# functional observations
X_obs <- fpca.face(norm_mcf)$Yhat #with or without fpca.face(), doesn't make big difference

# data combined
# event, survival time, Z, functional covariates
test_df = tnbc_clinical
test_df = left_join(test_df, tnbc_class, by = "InternalId")
# remove patient 30
test_df = test_df[-which(test_df$InternalId == 30),]
            
test_df$patient_class = as.factor(test_df$patient_class)


data_combine = data.frame(event = ifelse(test_df$Censored == 1, 0,1), stime = test_df$`Survival_days_capped*`,
                          Age = test_df$AGE_AT_DX, Grade = as.factor(test_df$GRADE),#Patient_class = test_df$patient_class,
                          X_obs = I(X_obs)) 
n_common = dim(data_combine)[1]
###########################################################################
# Fit AFCM and LFCM using mgcv
###########################################################################
## Add variables related to numerical integration
### lmat: numeric integration of the functional term
data_combine$lmat <- I(matrix(1/p, ncol=p, nrow=n_common))
### tmat: time indices, we assume an equally-spaced grid of [0, 1] for example
data_combine$tmat <- #I(matrix(seq(0, 1, len=p), ncol=p, nrow=n_common, byrow=TRUE))
                   I(matrix(seq(min(common_r1), max(common_r1), len=p), ncol=p, nrow=n_common, byrow=TRUE))


## smoothed LAC, h_{is} is the identity function
data_combine$func_cov <- data_combine$X_obs ## specify the functional covariates to use
data_combine$t_int <- data_combine$tmat ## t_int helps to integrate the case when models have different tmat and lmat
data_combine$l_int <- data_combine$lmat

fit_afcm <- gam(stime ~  Age + #Grade + #Patient_class + 
                ti(t_int, func_cov, by=l_int, bs=c("cr","cr"), k=c(k,k), mc=c(FALSE,TRUE)) 
                ,weights=event, data=data_combine, family=cox.ph())

## Fit LFCM
fit_lfcm <- gam(stime ~ Age + #Grade + #Patient_class + 
                s(t_int, by=l_int*func_cov, bs="cr", k=k) 
                , weights=event, data=data_combine, family=cox.ph())

## add other variables used in model fitting, required in predict() function
### in practice, we replicate the first row in final grid since it won't incluence estimated functional surface
sample1 <- data.frame("Age" = data_combine[1,c("Age")])# for 1 variable so that the column name is kept  # c("Age", "Grade")]  #"Patient_class")]


# extract estimates
# AFCM
grid_coef <- cal_grid(grid_length = 100, range_x = c(min(X_obs), max(X_obs)), range_s = c(min(common_r1), max(common_r1))) #range_s = c(0,1))
sample_rep <- do.call("rbind", replicate(nrow(grid_coef), sample1, simplify = FALSE)) # repeat first row of scalar covariates 
grid_coef <- cbind(grid_coef, sample_rep)

real_coef_afcm <- predict(fit_afcm, newdata = grid_coef, type = 'terms')

real_coef_afcm <- matrix(real_coef_afcm[,"ti(t_int,func_cov):l_int"], ncol = sqrt(nrow(grid_coef)), nrow = sqrt(nrow(grid_coef)), byrow = FALSE) # re-organize to matrix form
# LFCM
real_coef_lfcm <- predict(fit_lfcm, newdata = grid_coef, type = 'terms')
real_coef_lfcm <- matrix(real_coef_lfcm[,"s(t_int):l_int * func_cov"], ncol = sqrt(nrow(grid_coef)), nrow = sqrt(nrow(grid_coef)), byrow = FALSE) # re-organize to matrix form
```

## Plot AFCM & LFCM surface
```{r, warning=FALSE}
par(mfrow = c(1,2))
# Plot AFCM surface
real_surf_afcm <- vis_surf(coef = real_coef_afcm, simulation = TRUE, transformation = FALSE, range_x = c(min(X_obs), max(X_obs)), range_s = c(min(common_r1), max(common_r1)), 
                           trans_name = "Estimates from AFCM ", y_name = "Morans correlation in P53")

plot(real_surf_afcm)
# Plot LFCM surface
real_surf_lfcm <- vis_surf(coef = real_coef_lfcm, simulation = TRUE, transformation = FALSE, range_x = c(min(X_obs), max(X_obs)), range_s = c(min(common_r1), max(common_r1)),
                          trans_name = "Estimates from LFCM")
                         
plot(real_surf_lfcm)

```


